In [1]:
# Diabetes

In [2]:
import pandas as pd 

In [3]:
# Pipeline

In [4]:
from sklearn.pipeline import Pipeline
import pipeline_utilities_June_9 as p_util
from pipeline_utilities_June_9 import X_y_set
import glob

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# X_feature_set() includes loading data, spliting X_train, X_test and y_train, y_test.
X_train, X_test, y_train, y_test = X_y_set()
                                                    

Loading the DataFrame...


Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                0.0     1.0       1.0        1.0  24.0     0.0     0.0   
...              ...     ...       ...        ...   ...     ...     ...   
253675           0.0     1.0       1.0        1.0  45.0     0.0     0.0   
253676           2.0     1.0       1.0        1.0  18.0     0.0     0.0   
253677           0.0     0.0       0.0        1.0  28.0     0.0     0.0   
253678           0.0     1.0       0.0        1.0  23.0     0.0     0.0   
253679           2.0     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                        0.0           0.0     0.0  ...            1.0   
1                        0.0           1.0     0.0  ...            0.0   
2                        0.0           0.0     1.0  ...            1.0   
3                        0.0           1.0     1.0  ...            1.0   
4                        0.0           1.0     1.0  ...            1.0   
...                      ...           ...     ...  ...            ...   
253675                   0.0           0.0     1.0  ...            1.0   
253676                   0.0           0.0     0.0  ...            1.0   
253677                   0.0           1.0     1.0  ...            1.0   
253678                   0.0           0.0     1.0  ...            1.0   
253679                   1.0           1.0     1.0  ...            1.0   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
0               0.0      5.0      18.0      15.0       1.0  0.0   9.0   
1               1.0      3.0       0.0       0.0       0.0  0.0   7.0   
2               1.0      5.0      30.0      30.0       1.0  0.0   9.0   
3               0.0      2.0       0.0       0.0       0.0  0.0  11.0   
4               0.0      2.0       3.0       0.0       0.0  0.0  11.0   
...             ...      ...       ...       ...       ...  ...   ...   
253675          0.0      3.0       0.0       5.0       0.0  1.0   5.0   
253676          0.0      4.0       0.0       0.0       1.0  0.0  11.0   
253677          0.0      1.0       0.0       0.0       0.0  0.0   2.0   
253678          0.0      3.0       0.0       0.0       0.0  1.0   7.0   
253679          0.0      2.0       0.0       0.0       0.0  0.0   9.0   

        Education  Income  
0             4.0     3.0  
1             6.0     1.0  
2             4.0     8.0  
3             3.0     6.0  
4             5.0     4.0  
...           ...     ...  
253675        6.0     7.0  
253676        2.0     4.0  
253677        5.0     2.0  
253678        5.0     1.0  
253679        6.0     2.0  

[253680 rows x 22 columns]

'Value Counts'

Diabetes_012
0.0    213703
2.0     35346
1.0      4631
Name: count, dtype: int64

'Shape'

(253680, 22)

Display X below:


HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0          1.0       1.0        1.0  40.0     1.0     0.0   
1          0.0       0.0        0.0  25.0     1.0     0.0   
2          1.0       1.0        1.0  28.0     0.0     0.0   
3          1.0       0.0        1.0  27.0     0.0     0.0   
4          1.0       1.0        1.0  24.0     0.0     0.0   
...        ...       ...        ...   ...     ...     ...   
253675     1.0       1.0        1.0  45.0     0.0     0.0   
253676     1.0       1.0        1.0  18.0     0.0     0.0   
253677     0.0       0.0        1.0  28.0     0.0     0.0   
253678     1.0       0.0        1.0  23.0     0.0     0.0   
253679     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
0                        0.0           0.0     0.0      1.0  ...   
1                        0.0           1.0     0.0      0.0  ...   
2                        0.0           0.0     1.0      0.0  ...   
3                        0.0           1.0     1.0      1.0  ...   
4                        0.0           1.0     1.0      1.0  ...   
...                      ...           ...     ...      ...  ...   
253675                   0.0           0.0     1.0      1.0  ...   
253676                   0.0           0.0     0.0      0.0  ...   
253677                   0.0           1.0     1.0      0.0  ...   
253678                   0.0           0.0     1.0      1.0  ...   
253679                   1.0           1.0     1.0      0.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
0                 1.0          0.0      5.0      18.0      15.0       1.0   
1                 0.0          1.0      3.0       0.0       0.0       0.0   
2                 1.0          1.0      5.0      30.0      30.0       1.0   
3                 1.0          0.0      2.0       0.0       0.0       0.0   
4                 1.0          0.0      2.0       3.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
253675            1.0          0.0      3.0       0.0       5.0       0.0   
253676            1.0          0.0      4.0       0.0       0.0       1.0   
253677            1.0          0.0      1.0       0.0       0.0       0.0   
253678            1.0          0.0      3.0       0.0       0.0       0.0   
253679            1.0          0.0      2.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
0       0.0   9.0        4.0     3.0  
1       0.0   7.0        6.0     1.0  
2       0.0   9.0        4.0     8.0  
3       0.0  11.0        3.0     6.0  
4       0.0  11.0        5.0     4.0  
...     ...   ...        ...     ...  
253675  1.0   5.0        6.0     7.0  
253676  0.0  11.0        2.0     4.0  
253677  0.0   2.0        5.0     2.0  
253678  1.0   7.0        5.0     1.0  
253679  0.0   9.0        6.0     2.0  

[253680 rows x 21 columns]

y


array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [2.]])

X_train


HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
153605     0.0       0.0        1.0  23.0     0.0     0.0   
209016     1.0       0.0        0.0  25.0     1.0     0.0   
24047      0.0       0.0        1.0  23.0     0.0     0.0   
70479      0.0       1.0        1.0  29.0     0.0     0.0   
114169     0.0       0.0        1.0  32.0     0.0     0.0   
...        ...       ...        ...   ...     ...     ...   
229119     0.0       0.0        0.0  20.0     1.0     0.0   
5192       0.0       0.0        1.0  23.0     0.0     0.0   
208780     1.0       1.0        1.0  17.0     1.0     0.0   
229611     1.0       0.0        0.0  30.0     1.0     0.0   
128037     1.0       0.0        1.0  21.0     1.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
153605                   0.0           0.0     1.0      1.0  ...   
209016                   0.0           1.0     0.0      1.0  ...   
24047                    0.0           1.0     1.0      1.0  ...   
70479                    0.0           1.0     0.0      1.0  ...   
114169                   0.0           1.0     0.0      1.0  ...   
...                      ...           ...     ...      ...  ...   
229119                   0.0           0.0     0.0      1.0  ...   
5192                     0.0           0.0     1.0      1.0  ...   
208780                   1.0           1.0     1.0      1.0  ...   
229611                   0.0           1.0     1.0      1.0  ...   
128037                   0.0           1.0     0.0      0.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
153605            1.0          0.0      3.0       0.0       0.0       0.0   
209016            1.0          0.0      4.0       0.0      30.0       1.0   
24047             1.0          0.0      2.0       0.0       0.0       0.0   
70479             1.0          0.0      1.0       0.0       0.0       0.0   
114169            1.0          0.0      1.0       0.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
229119            1.0          1.0      2.0       0.0      10.0       0.0   
5192              1.0          0.0      2.0       0.0       0.0       0.0   
208780            1.0          0.0      5.0       0.0      30.0       0.0   
229611            1.0          0.0      3.0       5.0       0.0       0.0   
128037            1.0          0.0      2.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
153605  1.0   2.0        6.0     8.0  
209016  1.0   8.0        4.0     7.0  
24047   1.0  10.0        4.0     2.0  
70479   0.0  11.0        6.0     8.0  
114169  1.0   5.0        5.0     7.0  
...     ...   ...        ...     ...  
229119  0.0   5.0        6.0     6.0  
5192    0.0  10.0        6.0     6.0  
208780  0.0  12.0        4.0     3.0  
229611  1.0   6.0        6.0     8.0  
128037  0.0  12.0        6.0     5.0  

[190260 rows x 21 columns]

X_test


HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
235899     1.0       0.0        1.0  23.0     1.0     0.0   
74852      0.0       0.0        1.0  22.0     1.0     0.0   
8205       1.0       1.0        1.0  26.0     1.0     0.0   
127632     1.0       0.0        1.0  39.0     0.0     0.0   
32021      0.0       0.0        1.0  22.0     1.0     0.0   
...        ...       ...        ...   ...     ...     ...   
108360     0.0       1.0        1.0  29.0     1.0     0.0   
8531       1.0       0.0        1.0  24.0     1.0     0.0   
183429     1.0       1.0        1.0  31.0     0.0     0.0   
52932      0.0       0.0        1.0  32.0     1.0     0.0   
94566      1.0       0.0        1.0  27.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
235899                   0.0           1.0     1.0      1.0  ...   
74852                    1.0           1.0     1.0      1.0  ...   
8205                     0.0           1.0     1.0      1.0  ...   
127632                   0.0           1.0     1.0      1.0  ...   
32021                    0.0           0.0     1.0      1.0  ...   
...                      ...           ...     ...      ...  ...   
108360                   0.0           1.0     1.0      1.0  ...   
8531                     0.0           0.0     1.0      1.0  ...   
183429                   0.0           1.0     0.0      0.0  ...   
52932                    0.0           0.0     1.0      1.0  ...   
94566                    0.0           1.0     1.0      1.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
235899            1.0          0.0      2.0       0.0       0.0       0.0   
74852             1.0          0.0      2.0       0.0       5.0       0.0   
8205              1.0          0.0      2.0       0.0       0.0       0.0   
127632            1.0          0.0      4.0       0.0       0.0       0.0   
32021             1.0          0.0      1.0       0.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
108360            0.0          1.0      1.0       7.0       0.0       0.0   
8531              1.0          0.0      3.0       0.0      30.0       1.0   
183429            1.0          0.0      4.0       0.0      30.0       0.0   
52932             1.0          0.0      4.0       0.0       5.0       1.0   
94566             1.0          0.0      3.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
235899  0.0  13.0        6.0     6.0  
74852   1.0   9.0        6.0     8.0  
8205    0.0  11.0        4.0     6.0  
127632  1.0  11.0        6.0     5.0  
32021   0.0  10.0        6.0     8.0  
...     ...   ...        ...     ...  
108360  0.0   6.0        5.0     6.0  
8531    0.0   9.0        4.0     1.0  
183429  0.0  10.0        4.0     7.0  
52932   0.0  10.0        6.0     3.0  
94566   0.0   8.0        6.0     8.0  

[63420 rows x 21 columns]

y_train


array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [2.]])

y_test


array([[0.],
       [2.],
       [0.],
       ...,
       [0.],
       [2.],
       [0.]])

In [22]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(190260, 21)
(190260, 1)
(63420, 21)
(63420, 1)


In [7]:
from pipeline_utilities_June_9 import My_X_StandardScaler
from sklearn.preprocessing import StandardScaler

X_train_standardscaled, X_test_standardscaled = My_X_StandardScaler(X_train, X_test)


X_train_standardscaled


array([[ 1.15420503,  1.16522001,  0.19721658, ...,  1.62831366,
         0.96216302, -0.02663369],
       [-0.86639719, -0.85820702,  0.19721658, ...,  0.31822056,
        -1.06486761,  0.45601471],
       [-0.86639719, -0.85820702, -5.07056758, ..., -0.99187255,
        -1.06486761,  0.45601471],
       ...,
       [ 1.15420503, -0.85820702,  0.19721658, ..., -1.64691911,
         0.96216302,  0.9386631 ],
       [-0.86639719, -0.85820702,  0.19721658, ..., -0.336826  ,
        -0.05135229,  0.45601471],
       [-0.86639719,  1.16522001,  0.19721658, ...,  0.64574383,
         0.96216302,  0.45601471]])

X_test_standardscaled


array([[-0.86639719, -0.85820702,  0.19721658, ..., -0.99187255,
        -0.05135229, -1.95722726],
       [ 1.15420503, -0.85820702,  0.19721658, ..., -2.30196566,
         0.96216302, -2.43987566],
       [-0.86639719, -0.85820702,  0.19721658, ..., -1.97444238,
         0.96216302, -0.50928208],
       ...,
       [-0.86639719, -0.85820702,  0.19721658, ...,  0.31822056,
        -0.05135229, -0.99193048],
       [ 1.15420503, -0.85820702,  0.19721658, ..., -0.00930272,
        -1.06486761,  0.45601471],
       [-0.86639719, -0.85820702,  0.19721658, ..., -1.64691911,
        -0.05135229, -0.50928208]])

In [8]:
from sklearn.preprocessing import MinMaxScaler
from pipeline_utilities_June_9 import My_MinMaxScaler

In [9]:
X_train_MinMaxscaled, X_test_MinMaxscaled = My_MinMaxScaler(X_train, X_test)

MinMax X_train:


array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.71428571],
       [0.        , 0.        , 1.        , ..., 0.66666667, 0.6       ,
        0.85714286],
       [0.        , 0.        , 0.        , ..., 0.33333333, 0.6       ,
        0.85714286],
       ...,
       [1.        , 0.        , 1.        , ..., 0.16666667, 1.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.5       , 0.8       ,
        0.85714286],
       [0.        , 1.        , 1.        , ..., 0.75      , 1.        ,
        0.85714286]])

MinMax X_test:


array([[0.        , 0.        , 1.        , ..., 0.33333333, 0.8       ,
        0.14285714],
       [1.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.08333333, 1.        ,
        0.57142857],
       ...,
       [0.        , 0.        , 1.        , ..., 0.66666667, 0.8       ,
        0.42857143],
       [1.        , 0.        , 1.        , ..., 0.58333333, 0.6       ,
        0.85714286],
       [0.        , 0.        , 1.        , ..., 0.16666667, 0.8       ,
        0.57142857]])

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from pipeline_utilities_June_9 import My_LinearRegression
from pipeline_utilities_June_9 import r2_adj
from sklearn.model_selection import cross_val_score
import numpy as np


In [11]:
mse, r2, rmse, score, adj_score, cross_validation_score = My_LinearRegression(X_train, X_test, y_train, y_test)

mse: 0.40496247726964274
R2: 0.16845301788706235
root mean squared error:  0.6363666217438205
score:  1.0
Adjusted R2:  1.0
All scores: [0.17667349 0.17044035 0.17175584 0.17541596 0.174253  ]
Mean score: 0.17370772912790783
Standard Deviation: 0.002302030668972138


Classification

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from pipeline_utilities_June_9 import Standard_LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier

In [13]:
#lr_train, lr_test = Standard_LogisticRegression(X_train_standardscaled, X_test_standardscaled, y_train, y_test)
#train_scores, test_scores = KNeighborsClassifier(X_train_standardscaled, X_test_standardscaled, y_train, y_test)

In [16]:
from pipeline_utilities_June_9 import Standard_Classification
from pipeline_utilities_June_9 import Standard_LogisticRegression
from pipeline_utilities_June_9 import Standard_RandomForestClassifier
from pipeline_utilities_June_9 import Standard_Extra_Tree_Classifier
from pipeline_utilities_June_9 import Standard_DecisionTreeModel
from pipeline_utilities_June_9 import KNeighborsClassifier

In [18]:

Standard_Classification(X_test_standardscaled, X_test_standardscaled, y_train, y_test)


/Users/avalee/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Found input variables with inconsistent numbers of samples: [63420, 190260]

In [19]:
from pipeline_utilities_June_9 import MinMax_Classification
from pipeline_utilities_June_9 import MinMax_LogisticRegression
from pipeline_utilities_June_9 import MinMax_RandomForestClassifier
from pipeline_utilities_June_9 import MinMax_Extra_Tree_Classifier
from pipeline_utilities_June_9 import MinMax_DecisionTreeModel
from pipeline_utilities_June_9 import KNeighborsClassifier

In [20]:
MinMax_Classification(X_train_MinMaxscaled, X_test_MinMaxscaled, y_train, y_test)

UnboundLocalError: local variable 'LogisticRegression' referenced before assignment

In [ ]:
#lr_train_MinMax, lr_test_MinMax = MinMax_LogisticRegression(X_train_MinMaxscaled, X_test_MinMaxscaled, y_train, y_test)
#train_scores, test_scores = KNeighborsClassifier(X_train_MinMaxscaled, X_test_MinMaxscaled, y_train, y_test)

/Users/avalee/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training Data Score: 0.8460580258593504
Testing Data Score: 0.8477136549984232


TypeError: KNeighborsClassifier.__init__() takes from 1 to 2 positional arguments but 5 were given

In [ ]:
#from sklearn.svm import SVC 
#from pipeline_utilities_scrap import SupportVentorMachine

In [ ]:
#svm_train, svm_test = SupportVentorMachine(X_train, X_test, y_train, y_test)

/Users/avalee/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy: 0.842
Test Accuracy: 0.844


array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
# Train the KNN(K Nearest Neighbors) model with the best k value
# Note that k: 9 seems to be the best choice for this dataset
#knn = KNeighborsClassifier(n_neighbors=9)
# knn.fit(X_train_scaled, y_train)
# print('k=9 Test Acc: %.3f' % knn.score(X_test_scaled, y_test))